name: kick_admin
description: Kick Admin Package
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  logger: ^1.1.0
  equatable: ^2.0.3
  http: ^0.13.4
  meta: ^1.3.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  uuid: ^3.0.4
  go_router: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  bloc_test: ^9.0.1
  test: ^1.17.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true